/*******************************************************************************
 *
 * EcoViz -  a tool for visual analysis and photo‐realistic rendering of forest
 * landscape model simulations
 * Copyright (C) 2025  B. Merry
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 ********************************************************************************/
/**
 * @file
 *
 * Utilities for retrieving GLSL or CL source strings that have been baked
 * into the executable. The corresponding C++ file is generated by
 * @c source2cpp.py.
 */

#ifndef SOURCE2CPP_H
#define SOURCE2CPP_H

#include <common/debug_unordered_map.h>
#include <common/debug_string.h>

/**
 * Retrieve the map from source filenames to source content.
 */
const uts::unordered_map<uts::string, uts::string> &getSourceMap();

/**
 * Retrieve a source by filename.
 *
 * @param filename     The original filename, with path information excluded
 * @throw std::invalid_argument If the source does not exist
 */
const uts::string &getSource(const uts::string &filename);

#endif /* !SOURCE2CPP_H */
